#!/usr/bin/env bash

projectDirs=$(cat ~/.projectdirs 2>/dev/null || echo "~/Projects")
projectDirs=$(eval echo $projectDirs)  # This expands ~ to actual home path

declare -A projectPaths

while IFS= read -r fullPath; do
    projectName=$(basename "$fullPath")
    projectPaths["$projectName"]="$fullPath"
done < <(find $projectDirs -mindepth 1 -maxdepth 1 -type d)

projects=$(printf '%s\n' "${!projectPaths[@]}")
selected=$(printf "$projects" | bemenu -p "Open project" -P ">" -l 10)

if [ -n "$selected" ]; then
	sessionName=$(printf "project-$selected")
    projectPath="${projectPaths[$selected]}"

	echo "$projectPath"

	cd "$projectPath" && $TERMINAL -e zellij a "$sessionName" -c &
fi
