#!/usr/bin/env bash

all=(shutdown reboot suspend logout lockscreen)

show=("${all[@]}")

declare -A texts
texts[lockscreen]="lock screen"
texts[logout]="log out"
texts[suspend]="suspend"
# texts[hibernate]="hibernate"
texts[reboot]="reboot"
texts[shutdown]="shut down"

declare -A actions
actions[lockscreen]="loginctl lock-session ${XDG_SESSION_ID-}"
actions[logout]="loginctl terminate-session ${XDG_SESSION_ID-}"
actions[suspend]="systemctl suspend"
# actions[hibernate]="systemctl hibernate"
actions[reboot]="systemctl reboot"
actions[shutdown]="systemctl poweroff"

action=$(for entry in "${show[@]}"; do 
    echo "${texts[$entry]}" 
done | bemenu -p "Power menu" -l 10)

echo "${actions[$action]}"
